services:
  gateway:
    extends:
      file: api_gateway/docker-compose.yml
      service: gateway

  userapi:
    extends:
      file: user/docker-compose.yml
      service: userapi

  userapi_db:
    extends:
      file: user/docker-compose.yml
      service: userapi_db

  userapi_nginx:
    extends:
      file: user/docker-compose.yml
      service: userapi_nginx
  
  post_pg:
    extends:
      file: post/docker-compose.yml
      service: post_pg
  
  postapp:
    extends:
      file: post/docker-compose.yml
      service: postapp
  
  post-nginx:
    extends:
      file: post/docker-compose.yml
      service: post-nginx
  
  uprefapp:
    extends:
      file: user-preferences/docker-compose.yml
      service: uprefapp

  upref_pg:
    extends:
      file: user-preferences/docker-compose.yml
      service: upref_pg

  recapp:
    extends:
      file: recomendations/docker-compose.yml
      service: recapp
  
  rec_pg:
    extends:
      file: recomendations/docker-compose.yml
      service: rec_pg

  posttag_pg:
    extends: 
      file: common-db/docker-compose.yml
      service: posttag_pg

  evcollapp:
    extends:
      file: event-collector/docker-compose.yml
      service: evcollapp

  scheudleapp:
    extends: 
      file: schedule/docker-compose.yml
      service: scheduleapp

  schedule_pg:
    extends: 
      file: schedule/docker-compose.yml
      service: schedule_pg

  interaction-brk:
    extends:
      file: broker/docker-compose.yml
      service: interaction-brk
  
  notif:
    extends:
      file: notif/docker-compose.yml
      service: notif
  


  frontend:
    extends:
      file: frontend/docker-compose.yml
      service: frontend
    networks:
      - userapp_network
      - postapp_network
      - ms_network
    environment:
      - VITE_API_URL=http://localhost:8000/api/v1

networks:
  postapp_network:
    driver: bridge
  userapp_network:
    driver: bridge
  ms_network:
    driver: bridge
  recdb_network:
    driver: bridge
  uprefdb_network:
    driver: bridge
  scheduledb_network:
    driver: bridge

volumes:
  pgdata:
  staticfiles:
  postpgdata:
  uprefpgdata:
  recpgdata:
  schedulepgdata:
  posttagpgdata:
  rabbitmq_data: