server:
  port: 8000

spring:
  application:
    name: "API Gateway"
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: http://host.docker.internal:8081
              predicates:
                - Path=/user/**
            - id: post-service
              uri: http://host.docker.internal:8082
              predicates:
                - Path=/post/**
      

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway, httptrace
  endpoint:
    health:
      show-details: always