server:
  port: 8000
  

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: http://host.docker.internal:8081
              predicates:
                - Path=/api/v1/user/**
              filters:
                - StripPrefix=2

            - id: post-service
              uri: http://host.docker.internal:8082
              predicates:
                - Path=/api/v1/post/**
              filters:
                - StripPrefix=2

            - id: event-collector-service
              uri: http://host.docker.internal:8089
              predicates:
                - Path=/api/v1/evcollector/**
              filters:
                - StripPrefix=2

            - id: schedule-service
              uri: http://host.docker.internal:8083
              predicates:
                - Path=/api/v1/schedule/**
              filters:
                - StripPrefix=2
              
            - id: translation-service
              uri: http://host.docker.internal:8088
              predicates:
                - Path=/api/v1/translation/**
              filters:
                - StripPrefix=3



springdoc:
  swagger-ui:
    enabled: true
    urls:
      - name: "User Service"
        url: "/api/v1/user/schema/"
      - name: "Post Service"
        url: "/api/v1/post/v3/api-docs"
      - name: "Event Collector Service"
        url: "api/v1/evcollector/v3/api-docs"
      - name: "Schedule Service"
        url: "api/v1/schedule/v3/api-docs"
      - name: "Translation Service"
        url: "api/v1/translation/openapi.json"
    doc-expansion: list
    urls-primary-name: "User Service"
  
  api-docs:
    enabled: true
  
  enable-spring-security: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway, httptrace
  endpoint:
    health:
      show-details: always
