server:
  port: 8000
  

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: user-service
              uri: http://host.docker.internal:8081
              predicates:
                - Path=/api/v1/user/**
              filters:
                - StripPrefix=2

            - id: post-service
              uri: http://host.docker.internal:8082
              predicates:
                - Path=/api/v1/post/**
              filters:
                - StripPrefix=2

            - id: event-collector-service
              uri: http://host.docker.internal:8089
              predicates:
                - Path=/api/v1/evcollector/**
              filters:
                - StripPrefix=2

            - id: user-preferences-service
              uri: http://host.docker.internal:8086
              predicates:
                - Path=/api/v1/upref/**
              filters:
                - StripPrefix=2



springdoc:
  swagger-ui:
    enabled: true
    urls:
      - name: "User Service"
        url: "/api/v1/user/schema/"
      - name: "Post Service"
        url: "/api/v1/post/v3/api-docs"
      - name: "Event Collector Service"
        url: "api/v1/evcollector/v3/api-docs"
      - name: "User Preferences Service"
        url: "api/v1/upref/v3/api-docs"
    doc-expansion: list
    urls-primary-name: "User Service"
  
  api-docs:
    enabled: true
  
  enable-spring-security: false

management:
  endpoints:
    web:
      exposure:
        include: health, info, gateway, httptrace
  endpoint:
    health:
      show-details: always
