services:
  interaction-brk:
    image: rabbitmq:3-management
    container_name: interaction-brk
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: adminpassword
    volumes:
      - ./init-users.sh:/docker-entrypoint-initdb.d/init-users.sh:ro
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ms_network  

volumes:
  rabbitmq_data:
networks:
  ms_network: