services:
  interaction-brk:
    image: rabbitmq:3-management
    container_name: interaction-brk
    ports:
      - "5672:5672"
      - "15672:15672"

    volumes:
      - ./definitions.json:/etc/rabbitmq/definitions.json

    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: >
        -rabbitmq_management load_definitions "/etc/rabbitmq/definitions.json"
    networks:
      - ms_network  

volumes:
  rabbitmq_data:
networks:
  ms_network: